services:
  backend:
    container_name: blackjack-service
    image: blackjack-service:dev
    build:
      context: ../../producto-service-main/producto-service-main
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=
    ports:
      - "8082:8082"
    restart: unless-stopped
  conteo:
    container_name: conteo-service
    image: conteo-service:dev
    build:
      context: ../../conteo-service-master
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8083
      - JAVA_OPTS=
    ports:
      - "8083:8083"
    restart: unless-stopped
